# Signal timing constants
YELLOW_TIME = 3
ALL_RED_TIME = 2
MIN_GREEN_TIME = 5

NUM_EPISODES_TRAIN = 100
SIMULATION_LIMIT_TRAIN = 3600
UPDATE_FREQUENCY = 4
TARGET_UPDATE_FREQUENCY = 500
MODEL_SAVE_FREQUENCY = 25
LOG_SAVE_FREQUENCY = 1

SIMULATION_LIMIT_TEST = 10000

SAFE_HEADWAY = 1.0
COLLISION_DISTANCE = 1.0

STRAIGHT_TRAFFIC_RATIO = 0.8
MINOR_TO_MAJOR_TRAFFIC_RATIO = 0.25

TURN_RATIO = 0.1
